### ISSUE TITLE
Skewed p-value distribution

### ISSUE THREAD

**Issue by kimkh415** [gqi/DAESC#2]
Hello DAESC team,

I have a question about interpreting the result using the DAESC-MIX model. I have tested ~10000 genes for allelic imbalance among three conditions. Then I plotted a histogram of p-values. 
<img src="https://user-images.githubusercontent.com/32252748/225373234-287953c3-4f31-40d4-8b93-7b4fc73f4bb9.png" width="300" height="300">

Looking at the p-value distribution, it is very skewed, identifying almost all genes as significant.
Can you share your insights on this?

The dataset used here is 10X Visium.

Thank you!

**Comment by gqi** [comment]
DAESC-Mix is developed for datasets with many individuals (e.g. >20). It can lead to overfitting when the number of individuals is small, which is likely to have caused the skewed p-values. I recall you have 2 conditions and 2 individuals per condition. For this application I would suggest using DAESC-BB.

**Comment by seanken** [comment]
Hey! Following up (I am working with Kwanho on this, excited to play more with DAESC, seems really cool!) we've tested in a few settings (ranging from a few samples per condition to a couple dozen) and had the same issue (both an issue with the bb and mix methods). Digging into it looks like the issue only happens when we have >2 conditions (so when the input model matrix, x, has >1 column). Is that expected behavior? Looking at the code from DAESC I am guessing it is built to assume there is only one column in the model matrix (think both setting param=param.init[-2] when fitting the null model and using df=1 in the p-value calculation are built on this assumption I think, assuming I am following along with the code correctly?), though not 100% sure? Thanks!

**Comment by seanken** [comment]
Hey,

Awesome, thanks! Excited to give it a try!

Best wishes,

Sean

**Comment by seanken** [comment]
One more thought: looks like the code still uses df=1 for the LRT test (the pchisq command), but if I remember right I think that doesn't work if the null hypothesis and the full model differ by more than 1 variable (will lead to overinflated p-values in other cases I think)?

**Comment by gqi** [comment]
Sorry for missing this. I updated the `df` to be `ncol(X)-ncol(XNull)`. Thanks for looking at the code!

**Comment by seanken** [comment]
Thanks!

**Comment by kimkh415** [comment]
Thanks again Guanghao! Will close this issue now.
